[toolchain]
anchor = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pyth_stub = "BjLKu19Kbqnc43dSDD7aKSrTxahskhkAsKh85Pmmewr2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
